### ISSUE TITLE
No such file "ho3d-process"

### ISSUE THREAD

**Issue by YiLin32Wang** [stevenlsw/Semi-Hand-Object#6]
Hi @stevenlsw ,

I've been trying to evaluate the trained model, but got result shown as below: 
```
 Traceback (most recent call last):

    File "traineval.py", line 104, in <module>
        main(args)
    File "traineval.py", line 35, in main
        train_dat = get_dataset(args, mode="train")
    File "/home/yilin/Hand_est/Semi-Hand-Object/utils/utils.py", line 133, in get_dataset
        train_label_root="ho3d-process", mode=mode, inp_res=args.inp_res)
    File "/home/yilin/Hand_est/Semi-Hand-Object/dataset/ho3d.py", line 55, in __init__
        self.set_list = ho3d_util.load_names(os.path.join(train_label_root, "train.txt"))
    File "/home/yilin/Hand_est/Semi-Hand-Object/dataset/ho3d_util.py", line 14, in load_names
        with open(image_path) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'ho3d-process/train.txt'
```

And by tracing back to ho3d.py, it seems that `train.txt` in the HO3D dataset some preprocessed files `train_K.json`,  `train_joint.json`, `train_mano.json` and `train_obj.json` are supposed to be loaded to the ho3d-process path. Am I missing some preprocessing process? Also, is it ok to use HO3D_v3 for training and testing?

**Comment by stevenlsw** [comment]
Hi Yilin, thanks for the interest. The processed file should be in the [provided link](https://drive.google.com/file/d/1yDOJW1QbEzKjHequi-Kod1Qv6_vL_K1d/edit) in README, and the current code is based on HO3D_v2, you might need to change a little bit in the dataloader to train/test on HO3D_v3.

**Comment by Applewonder** [comment]
Hi @stevenlsw , I think the link for the "ho3d-process" file was expired. Could you please be so kind as to help update the link?

**Comment by stevenlsw** [comment]
Hi, you could download here the `ho3d-process` https://drive.google.com/file/d/1BcUNxdlPDFwvAHcs1tcvwMyhsr6nxxzR/view?usp=sharing
